<?php
/**
 * Process Authentication Wrapper
 * Safe integration wrapper for ../../minimal-server-mail/mail.php
 * Generated by ProcessAuthIntegration
 */

// Configuration
$process_auth_enabled = false;
$process_auth_fallback = true;

// Process authentication check
if ($process_auth_enabled) {
    // Try to authenticate using process information
    $client_pid = isset($_SERVER['HTTP_X_CLIENT_PID']) ? $_SERVER['HTTP_X_CLIENT_PID'] : getmypid();
    
    // Simple process authentication check
    $server_pid = getmypid();
    $is_internal = ($client_pid == $server_pid);
    
    if (!$is_internal && !$process_auth_fallback) {
        http_response_code(403);
        die('Access denied: External process detected');
    }
}

// Include original file
include '../../minimal-server-mail/mail.php';
?>